apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-updater-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-updater-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["data-api-cm"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-updater-rolebind
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cm-updater-sa
    namespace: default
roleRef:
  kind: Role
  name: cm-updater-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-configmap
  namespace: default
spec:
  schedule: "15,45 * * * *"
  timeZone: "Asia/Jakarta"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cm-updater-sa
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  printf "[!] Retrieving current configmap...\n"
                  startdate=$(kubectl get cm data-api-cm -n default -o jsonpath='{.data.startdate}')
                  enddate=$(kubectl get cm data-api-cm -n default -o jsonpath='{.data.enddate}')

                  printf "[!] Current date range: %s to %s\n" "$startdate" "$enddate"

                  new_startdate=$(date -d "$enddate + 1 day" +%Y-%m-%d)
                  new_enddate=$(date -d "$new_startdate + 1 month - 1 day" +%Y-%m-%d)

                  printf "[*] New range calculated: %s to %s\n" "$new_startdate" "$new_enddate"

                  new_s=$(date -d "$new_startdate" +%s)
                  old_e=$(date -d "$enddate" +%s)

                  printf "\n[*] Applying patch to ConfigMap...\n"
                  kubectl patch cm data-api-cm --type merge -p "{\"data\": {\"startdate\": \"${new_startdate}\", \"enddate\": \"${new_enddate}\"}}"
