apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: kserve
  labels:
    app: debian
spec:
  containers:
    - name: debian
      image: "debian:stable-slim"
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 32Mi
      command:
        - /bin/bash
        - -c
      args:
        - apt update; apt install curl nano -y; sleep infinity;
      volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
  volumes:
    - name: timezone
      hostPath:
        path: /usr/share/zoneinfo/Asia/Jakarta
        type: File
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: debian
  name: debian
  namespace: kserve
spec:
  clusterIP: ""
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: debian
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
