nfs:
  server: 10.140.0.7
  path: /shared/nfs

storageClass:
  name: nfs-sep
  allowVolumeExpansion: False
  reclaimPolicy: Delete
  archiveOnDelete: False
  volumeBindingMode: Immediate
  defaultClass: True
  provisionerName: nfs-sep

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
