airflow:
  executor: KubernetesExecutor
  fernetKey: "TnEG6lnZPoHNga6yjOL-tSOC2X2xuWiY18rtD3hW8JM="
  users:
    - username: ibrahim
      password: wazowski12344321
      role: Admin
      email: ibrahim@admin.example
      firstName: ibrahim
      lastName: tampan

###################################
## COMPONENT | Airflow Scheduler
###################################
scheduler:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

###################################
## COMPONENT | Airflow Webserver
###################################
web:
  webserverConfig:
    enabled: true
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 8080
    loadBalancerIP: ""

###################################
## COMPONENT | Airflow Workers
###################################
workers:
  enabled: false
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

###################################
## COMPONENT | Triggerer
###################################
triggerer:
  enabled: true
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

###################################
## COMPONENT | Flower
###################################
flower:
  enabled: false
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 5555
    loadBalancerIP: ""

###################################
## CONFIG | Airflow Logs
###################################
logs:
  persistence:
    enabled: false

###################################
## CONFIG | Airflow DAGs
###################################
dags:
  path: /opt/airflow/dags
  persistence:
    enabled: false
  gitSync:
    enabled: false
    image:
      repository: registry.k8s.io/git-sync/git-sync
      tag: v3.6.9
      pullPolicy: IfNotPresent
      uid: 65533
      gid: 65533
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    ## the url of the git repo
    ##
    ## ____ EXAMPLE _______________
    ##   # https git repo
    ##   repo: "https://github.com/USERNAME/REPOSITORY.git"
    ##
    ## ____ EXAMPLE _______________
    ##   # ssh git repo
    ##   repo: "git@github.com:USERNAME/REPOSITORY.git"
    ##
    repo: ""

    ## the sub-path within your repo where dags are located
    ## - only dags under this path within your repo will be seen by airflow,
    ##   (note, the full repo will still be cloned)
    ##
    repoSubPath: ""

    ## the git branch to check out
    ##
    branch: master
    revision: HEAD
    depth: 1
    httpSecret: ""
    ## the key in `dags.gitSync.httpSecret` with your git username
    ##
    httpSecretUsernameKey: username
    ## the key in `dags.gitSync.httpSecret` with your git password/token
    ##
    httpSecretPasswordKey: password
    ## the name of a pre-created Secret with git ssh credentials
    ##
    sshSecret: ""
    ## the key in `dags.gitSync.sshSecret` with your ssh-key file
    ##
    sshSecretKey: id_rsa
    ## the string value of a "known_hosts" file (for SSH only)
    ## - [WARNING] known_hosts verification will be disabled if left empty, making you more
    ##   vulnerable to repo spoofing attacks
    ##
    ## ____ EXAMPLE _______________
    ##   sshKnownHosts: |-
    ##     <HOST_NAME> ssh-rsa <HOST_KEY>
    ##
    sshKnownHosts: ""
    ## the number of consecutive failures allowed before aborting
    ##  - the first sync must succeed
    ##  - a value of -1 will retry forever after the initial sync
    ##
    maxFailures: 0

###################################
## CONFIG | Kubernetes Ingress
###################################
ingress:
  enabled: true
  web:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    host: "airflow.ibrahim.net"
    ingressClassName: "nginx"
  flower:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    host: "flower.ibrahim.net"
    ingressClassName: "nginx"

###################################
## DATABASE | PgBouncer
###################################
pgbouncer:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

###################################
## DATABASE | Embedded Postgres
###################################
postgresql:
  enabled: false

###################################
## DATABASE | External Database
###################################
externalDatabase:
  type: postgres
  host: postgresql-0.postgresql-hl.postgresql.svc.cluster.local
  port: 5432
  database: data_warehouse_db
  user: airflow
  password: "d2F6b3dza2kK"

###################################
## DATABASE | Embedded Redis
###################################
redis:
  enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 6.2.14-debian-12-r17
    pullPolicy: IfNotPresent
  password: airflow
  master:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    persistence:
      enabled: true
      storageClass: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 4Gi
